### ISSUE TITLE
Bug with keep alive packet occasionally failing with following error

### ISSUE THREAD

**Issue by Aatu** [Lulz0rz/battle-node#3]
Code fails with following stack trace. I added some debug logging, and turns out sequence gets into 256 in some cases. Unfortunately I have no idea what causes this.

    
    TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:705:11)
    at Buffer.writeUInt8 (buffer.js:715:5)
    at BattleNode.keepalivePacket (/home/steam/arma/monitor/node_modules/battle-node/lib/index.js:229:8)
    at null.<anonymous> (/home/steam/arma/monitor/node_modules/battle-node/lib/index.js:43:23)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by Aatu** [comment]
Actually, looks like you already fixed it here: https://github.com/Lulz0rz/battle-node/pull/2/files, but I got an old version(?) from npm...

**Comment by Xstasy** [comment]
@Aatu Use ```sh npm install Lulz0rz/battle-node```
